// front-vue/src/components/atoms/Table/Table.vue
<template>
    <table class="table w-full" v-bind="$attrs">
      <thead>
        <tr>
          <th>#</th>
          <th 
            v-for="(column, index) in columns" 
            :key="index"
            v-bind="column.props"
          >
            {{ column.label || column.field }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(row, rowIndex) in data" :key="rowIndex">
          <th>{{ rowIndex + 1 }}</th>
          <td 
            v-for="(column, colIndex) in columns" 
            :key="colIndex"
            v-bind="column.props"
          >
            <template v-if="column.render">
              {{ column.render(row) }}
            </template>
            <template v-else>
              {{ row[column.field] }}
            </template>
          </td>
        </tr>
      </tbody>
    </table>
  </template>
  
  <script>
  export default {
    name: 'Table',
    props: {
      data: {
        type: Array,
        default: () => []
      },
      columns: {
        type: Array,
        required: true,
        validator: (value) => {
          return value.every(column => 
            typeof column.field === 'string' && 
            (column.label === undefined || typeof column.label === 'string') &&
            (column.props === undefined || typeof column.props === 'object') &&
            (column.render === undefined || typeof column.render === 'function')
          )
        }
      }
    }
  }
  </script>

// frontend/src/components/atoms/Table/Table.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { HTMLAttributes } from 'react'


export interface ColumnProps<T> {
    field: string;
    label?: string;
    props?: HTMLAttributes<HTMLTableCellElement>;
    render?: (value: T) => React.ReactNode;

}


interface TableProps<T> extends HTMLAttributes<HTMLTableElement> {
    data?: T[];
    columns: ColumnProps<T>[];
}

const Table = <T extends object>({ data, columns,...props }: TableProps<T>) => {
  return (
    <table className="table w-full" {...props}>
      <thead>
        <tr>
            <th>#</th>
          {columns.map((column, index) => (
            <th key={index} {...column.props}>
              {column.label || column.field}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {data && data.map((row, rowIndex) => (
          <tr key={rowIndex}>
            <th>{rowIndex + 1}</th>
            {columns.map((column, colIndex) => (
              <td key={colIndex} {...column.props}>
                {column.render ? column.render(row) : (row as Record<string, any>)[column.field]}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  )
}

export default Table
